Import Debian changes 8.0.0-1
groonga (8.0.0-1) unstable; urgency=medium

  * New upstream release.
  * debian/control
    - Bump Standards-Version, no other changes are required.

groonga (7.1.1-1) unstable; urgency=medium

  * New upstream release.
  * debian/control
    - Bump Standards-Version, no other changes are required.

groonga (7.1.0-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.
  * debian/control
    - Bump Standards-Version, no other changes are required.

groonga (7.0.9-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.

groonga (7.0.8-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.

groonga (7.0.7-1) unstable; urgency=medium

  * New upstream release.
  * debian/control
    - Bump version to 4.1.1 (no other changes are required)
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.

groonga (7.0.6-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.
  * debian/groonga-httpd.service
    - Ensure to create /var/run/groonga directory.

groonga (7.0.5-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.

groonga (7.0.4-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.
  * debian/control
    - Bump version to 4.0.0 (no other changes are required)

groonga (7.0.3-2) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.
  * debian/copyright
    - Add missing copyright about benchmark.

groonga (7.0.3-1) experimental; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.
  * debian/copyright
    - Add missing copyright about benchmark.

groonga (7.0.2-1) experimental; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.

groonga (7.0.1-1) experimental; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.

groonga (7.0.0-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.

groonga (6.1.5-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-a-bug-that-AND-optimization-may-skip-matched-rec.patch
    debian/patches/really-fix-a-bug-that-AND-optimization-may-skip-matc.patch
    - Drop needless patch files. These changes are already merged in
      Groonga 6.1.5.

groonga (6.1.4-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-a-bug-that-AND-optimization-may-skip-matched-rec.patch
    debian/patches/really-fix-a-bug-that-AND-optimization-may-skip-matc.patch
    - Apply patches to fix an index search bug that index search may
      not return records that should be matched.

groonga (6.1.3-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.
  * debian/libgroonga0.install
    - Drop removed file since Groonga 6.1.2.

groonga (6.1.1-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Refresh patch to fix FTBFS on kFreeBSD.
  * debian/control
    - Add dependency to support Zstd column compression.

groonga (6.1.0-2) unstable; urgency=medium

  * debian/patches/fix-nginx-FTBFS-on-kfreebsd.patch
    - Add patch to fix FTBFS on kFreeBSD.
  * debian/copyright
    - Add copyright about bundled ngx-mruby.

groonga (6.1.0-1) unstable; urgency=medium

  * New upstream release.
  * debian/control
    - Add missing dependency to lsb-base because of init.d script.

groonga (6.0.9-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-build-error-with-openssl-1.1.patch
    - Drop needless patch because it was fixed in upstream.

groonga (6.0.8-1) unstable; urgency=medium

  * New upstream release.

groonga (6.0.7-1) unstable; urgency=medium

  * New upstream release.
  * debian/patches/fix-nginx-build-error-with-openssl-1.1.patch
    - Update OpenSSL patch for bundled nginx 1.11.3

groonga (6.0.5-2) unstable; urgency=medium

  * debian/patches/fix-nginx-build-error-with-openssl-1.1.patch
    - Fix FTBFS with OpenSSL 1.1.0 (Closes: #828331)
  * debian/copyright
    - Update copyright year about vendor/mruby.

groonga (6.0.5-1) unstable; urgency=medium

  * New upstream release.

groonga (6.0.4-1) unstable; urgency=medium

  * New upstream release.
  * debian/control
    - Drop needless dependency to autotools-dev.
  * debian/groonga-httpd.service,
    debian/groonga-server-gqtp.service
    - Add Documentation= entry to service unit.
  * debian/groonga-httpd.default,
    debian/groonga-server-gqtp.default
    - Update default configuration in this release.

groonga (6.0.2-1) unstable; urgency=medium

  * Team upload.
  * New upstream release.
  * debian/control
    - Update standards version to 3.9.8.
    - Update compat level to 10.
    - Drop needless dependency to dh-autoreconf.
  * debian/upstream/signing-key.asc
    - Add signing key to check signature.
  * debian/watch
    - Add pgpsigurlmangle to verify the archive.
  * debian/groonga-bin.install
    - Drop man files which are not provided anymore.
    - Install missing grndb command.
  * debian/groonga-httpd.service
    - Make package description more clear.
    - Use EnvironmentFile directive to customize.
    - Drop unused Conflicts directive.
  * debian/groonga-gqtp.service
    - Make package description more clear.
    - Use server mode which does not fork.
  * debian/libgroonga0.install
    - Install missing functions plugin.
  * debian/copyright
    - Update copyright year.
  * debian/groonga-bin.lintian-overrides,
    debian/groonga-httpd.lintian-overrides,
    debian/groonga-plugin-suggest.lintian-overrides
    - Suppress binary-without-manpage lintian warnings because
      upstream dropped man support explicitly.
  * debian/rule
    - Remove bundled jquery and underscore correctly.

groonga (6.0.1-1) unstable; urgency=medium

  * Team upload.
  * New upstream release.
  * debian/control
    - Use Architecture: any to support more architectures.
    - Drop transitional groonga-server-http package.
  * debian/rules
    - Remove needless DEB_BUILD_HARDENING flag.
    - Disable static library.
  * debian/groonga-httpd.default
    - Set variables to enable fast phrase search feature.

groonga (6.0.0-1) unstable; urgency=medium

  * Team upload.
  * New upstream release.
  * debian/control
    - Fix "undefined reference to `GRN_ATOMIC_ADD_EX'" on mips,mipsel,m68k.
      Closes: #770243
    - Update standards-version to 3.9.7
    - Add SSL/TLS dependency which is required by groonga-httpd.
  * patches/*
    - Remove needless use-jquery-flot-0.8.3.patch because it is fixed
      in upstream.

groonga (5.1.2-1) unstable; urgency=medium

  * Team upload.
  * New upstream release.
  * patches/use-jquery-flot-0.8.3.patch
    - Fix source-is-missing lintian error.
  * debian/rules,debian/control
    - Fix automake related FTBFS issue which is caused by added patch.

groonga (5.1.1-1) unstable; urgency=medium

  * Team upload.
  * New upstream release.
  * debian/copyright
    - Fix I:unused-file-paragraph-in-dep5-copyright paragraph notifications.
  * debian/rules
    - Fix FTBFS on ppc64el due to outdated config.guess in vendor/onigmo-source.

groonga (5.1.0-1) unstable; urgency=medium

  * Team upload.
  * New upstream release.
  * Import upstream debian/* changes.
    - Closes: #799167, #800451
  * Do not delete conffiles which are owned by other packages
    - Closes: #773029
  * debian/source.lintian-overrides
    - Suppress source-is-missing error.
  * debian/tests/*
    - Add files for autopkgtest.

groonga (4.0.6.1-2) unstable; urgency=low

  * Team upload.
  * debian/control
    - Support amd64,i386,kfreebsd-amd64,kfreebsd-i386 and ppc64el only
      because of build failure for other architectures. It is a just workaroud. 
    - Follow Standard-Version to 3.9.6.

groonga (4.0.6.1-1) unstable; urgency=low

  * Team upload.
  * debian/copyright
    - Add missing copyright about sphinx bundled js/css.
    - Add missing copyright about jquery-ui css.
  * Initial upload to Debian (Closes: #732055)

groonga (4.0.6-1) unstable; urgency=low

  * New upstream release.

groonga (4.0.5-1) unstable; urgency=low

  * New upstream release.
  * debian/copyright
    - Add missing copyright about bundled .js and .css
  * debian/missing-sources
    - Add missing-sources for bundled JavaScript.

groonga (4.0.4-1) unstable; urgency=low

  * New upstream release.

groonga (4.0.3-1) unstable; urgency=low

  * New upstream release.

groonga (4.0.2-1) unstable; urgency=low

  * New upstream release.

groonga (4.0.1-2) unstable; urgency=low

  * debian/control
    - Add a missing pkg-config dependency to libgroonga-dev.
    - Depend on mecab-naist-jdic instead of mecab-ipadic-utf8 because
      mecab-naist-jdic is a replacement of mecab-ipadic-utf8.

groonga (4.0.1-1) unstable; urgency=low

  * New upstream release.

groonga (4.0.0-1) unstable; urgency=low

  * New upstream release.

groonga (3.1.2-1) unstable; urgency=low

  * New upstream release.
  * debian/control
    - Add proper description to fix "duplicate-long-description" lintian warning
      for groonga-server-gqtp and groonga-server-http packages.
    - Remove needless period to fix I:description-synopsis-might-not-be-phrased-properly lintian warning.
    - Use "all" in Architecture field to fix I: package-contains-no-arch-dependent-files
      lintian warning for groonga-example package.
  * debian/rules
    - Add DEB_BUILD_HARDENING flag to fix lintian warning "hardening-no-relro" and
      "hardening-no-fortify-functions"

groonga (3.1.1-1) unstable; urgency=low

  * New upstream release.

groonga (3.1.0-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.9-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.8-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.7-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.6-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.5-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.4-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.3-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.2-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.1-1) unstable; urgency=low

  * New upstream release.

groonga (3.0.0-1) unstable; urgency=low

  * New upstream release.

groonga (2.1.2-1) unstable; urgency=low

  * New upstream release.

groonga (2.1.1-1) unstable; urgency=low

  * New upstream release.

groonga (2.1.0-1) unstable; urgency=low

  * New upstream release.

groonga (2.0.9-1) unstable; urgency=low

  * New upstream release.

groonga (2.0.8-1) unstable; urgency=low

  * New upstream release.

groonga (2.0.7-1) unstable; urgency=low

  * New upstream release.

groonga (2.0.6-1) unstable; urgency=low

  * New upstream release.
  * Split common tasks for server use into groonga-server-common package.
  * groonga-server and groonga-httpd require groonga-server-common package.

groonga (2.0.5-1) unstable; urgency=low

  * New upstream release.

groonga (2.0.4-1) unstable; urgency=low

  * New upstream release.

groonga (2.0.3-1) unstable; urgency=low

  * New upstream release.
  * Fix a bug that log_reopen command in logrotate uses wrong protocol.

groonga (2.0.2-1) unstable; urgency=low

  * New upstream release.
  * Set missing default values.

groonga (2.0.1-3) unstable; urgency=low

  * Fix default file path: /etc/default/groonga -> /etc/default/groonga-server
  * Use shutdown command for stop.

groonga (2.0.1-2) unstable; urgency=low

  * Fix bind address argument parameter.
    Patch by Masaharu IWAI. Thanks!!!

groonga (2.0.1-1) unstable; urgency=low

  * New upstream release.
  * grntest -> groonga-benchmark.
  * Remove groogna-tools package.

groonga (2.0.0-1) unstable; urgency=low

  * New upstream release.
  * Use HTTP as the default protocol.

groonga (1.3.0-1) unstable; urgency=low

  * New upstream release.
  * groonga-server doesn't require groonga-munin-plugins.
    Suggested by Masaharu IWAI. Thanks!!!

groonga (1.2.9-1) unstable; urgency=low

  * New upstream release.

groonga (1.2.8-1) unstable; urgency=low

  * New upstream release.
  * Enable zlib support.
  * Enable lzo support.

groonga (1.2.7-1) unstable; urgency=low

  * New upstream release.

groonga (1.2.6-1) unstable; urgency=low

  * New upstream release.

groonga (1.2.5-1) unstable; urgency=low

  * New upstream release.

groonga (1.2.4-1) unstable; urgency=low

  * New upstream release.

groonga (1.2.3-1) unstable; urgency=low

  * New upstream release.

groonga (1.2.2-1) unstable; urgency=low

  * New upstream release.

groonga (1.2.1-1) unstable; urgency=low

  * New upstream release.

groonga (1.2.0-3) unstable; urgency=low

  * libgronga-dev: add missing libgroonga.so.

groonga (1.2.0-2) unstable; urgency=low

  * libgronga-dev: add missing libgroonga.so.

groonga (1.2.0-1) unstable; urgency=low

  * New upstream release.

groonga (1.1.0-1) unstable; urgency=low

  * New upstream release.

groonga (1.0.8-1) unstable; urgency=low

  * New upstream release.

groonga (1.0.7-1) unstable; urgency=low

  * New upstream release.

groonga (1.0.6-1) unstable; urgency=low

  * New upstream release.

groonga (1.0.5-1) unstable; urgency=low

  * New upstream release.

groonga (1.0.4-1) unstable; urgency=low

  * New upstream release.

groonga (1.0.3-1) lucid; urgency=low

  * New upstream release.

groonga (1.0.2-1) lucid; urgency=low

  * New upstream release.

groonga (1.0.1-1) lucid; urgency=low

  * New upstream release.

groonga (1.0.0-1) lucid; urgency=low

  * New upstream release.

groonga (0.7.7-1) lucid; urgency=low

  * New upstream release.

groonga (0.7.6-2) unstable; urgency=low

  * Split packages.

groonga (0.7.6) unstable; urgency=low

  * New upstream release.

groonga (0.7.4) unstable; urgency=low

  * New upstream release.

groonga (0.1.9) unstable; urgency=low

  * New upstream release.

groonga (0.1.6) unstable; urgency=low

  * New upstream release.

groonga (0.1.5) unstable; urgency=low

  * Initial release.